"""initial_schema

Revision ID: 1994374f0ca5
Revises: 
Create Date: 2026-06-11 12:55:00.396787
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1994374f0ca5'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('asset_models',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('purchase_date', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('Available', 'Unavailable', 'Maintenance', 'Damaged', name='asset_model_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_asset_models_category'), 'asset_models', ['category'], unique=False)
    op.create_index(op.f('ix_asset_models_name'), 'asset_models', ['name'], unique=False)
    op.create_table('otp_verifications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('otp_code', sa.String(length=6), nullable=False),
    sa.Column('purpose', sa.Enum('email_verify', 'password_reset', name='otp_purpose'), nullable=False),
    sa.Column('is_used', sa.Boolean(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_otp_verifications_user_id'), 'otp_verifications', ['user_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('role', sa.Enum('admin', 'user', name='user_role'), nullable=False),
    sa.Column('profile_image', sa.String(length=500), nullable=True),
    sa.Column('department', sa.String(length=255), nullable=True),
    sa.Column('is_email_verified', sa.Boolean(), nullable=True),
    sa.Column('reliability_score', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('asset_images',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('asset_model_id', sa.UUID(), nullable=False),
    sa.Column('image_url', sa.String(length=500), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['asset_model_id'], ['asset_models.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_asset_images_asset_model_id'), 'asset_images', ['asset_model_id'], unique=False)
    op.create_table('asset_units',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('asset_model_id', sa.UUID(), nullable=False),
    sa.Column('unit_code', sa.String(length=50), nullable=False),
    sa.Column('serial_number', sa.String(length=100), nullable=True),
    sa.Column('condition', sa.Enum('Excellent', 'Good', 'Fair', 'Poor', 'Damaged', name='asset_condition'), nullable=False),
    sa.Column('status', sa.Enum('Available', 'Issued', 'Maintenance', 'Retired', name='asset_unit_status'), nullable=False),
    sa.Column('qr_code_url', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['asset_model_id'], ['asset_models.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_asset_units_asset_model_id'), 'asset_units', ['asset_model_id'], unique=False)
    op.create_index(op.f('ix_asset_units_unit_code'), 'asset_units', ['unit_code'], unique=True)
    op.create_table('audit_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=True),
    sa.Column('metadata', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_entity_type'), 'audit_logs', ['entity_type'], unique=False)
    op.create_index(op.f('ix_audit_logs_timestamp'), 'audit_logs', ['timestamp'], unique=False)
    op.create_table('bookings',
    sa.Column('booking_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('asset_model_id', sa.UUID(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('Pending', 'Approved', 'Rejected', 'Issued', 'Returned', 'Overdue', 'Cancelled', name='booking_status'), nullable=False),
    sa.Column('approval_notes', sa.Text(), nullable=True),
    sa.Column('approved_by', sa.UUID(), nullable=True),
    sa.Column('issued_at', sa.DateTime(), nullable=True),
    sa.Column('returned_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['asset_model_id'], ['asset_models.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('booking_id')
    )
    op.create_index(op.f('ix_bookings_asset_model_id'), 'bookings', ['asset_model_id'], unique=False)
    op.create_index(op.f('ix_bookings_user_id'), 'bookings', ['user_id'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_table('asset_assignment_history',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('asset_unit_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('booking_id', sa.UUID(), nullable=False),
    sa.Column('condition_before', sa.Enum('Excellent', 'Good', 'Fair', 'Poor', 'Damaged', name='asset_condition'), nullable=True),
    sa.Column('condition_after', sa.Enum('Excellent', 'Good', 'Fair', 'Poor', 'Damaged', name='asset_condition'), nullable=True),
    sa.Column('issued_at', sa.DateTime(), nullable=False),
    sa.Column('returned_at', sa.DateTime(), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['asset_unit_id'], ['asset_units.id'], ),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.booking_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_asset_assignment_history_asset_unit_id'), 'asset_assignment_history', ['asset_unit_id'], unique=False)
    op.create_table('asset_health_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('asset_unit_id', sa.UUID(), nullable=False),
    sa.Column('previous_condition', sa.Enum('Excellent', 'Good', 'Fair', 'Poor', 'Damaged', name='asset_condition'), nullable=True),
    sa.Column('current_condition', sa.Enum('Excellent', 'Good', 'Fair', 'Poor', 'Damaged', name='asset_condition'), nullable=False),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['asset_unit_id'], ['asset_units.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_asset_health_logs_asset_unit_id'), 'asset_health_logs', ['asset_unit_id'], unique=False)
    op.create_table('asset_image_history',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('asset_image_id', sa.UUID(), nullable=True),
    sa.Column('asset_model_id', sa.UUID(), nullable=False),
    sa.Column('old_image_url', sa.String(length=500), nullable=True),
    sa.Column('new_image_url', sa.String(length=500), nullable=True),
    sa.Column('action', sa.Enum('upload', 'replace', 'delete', name='image_action'), nullable=False),
    sa.Column('changed_by', sa.UUID(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['asset_image_id'], ['asset_images.id'], ),
    sa.ForeignKeyConstraint(['asset_model_id'], ['asset_models.id'], ),
    sa.ForeignKeyConstraint(['changed_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_asset_image_history_asset_model_id'), 'asset_image_history', ['asset_model_id'], unique=False)
    op.create_table('booking_unit_assignments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('booking_id', sa.UUID(), nullable=False),
    sa.Column('asset_unit_id', sa.UUID(), nullable=False),
    sa.Column('condition_before', sa.Enum('Excellent', 'Good', 'Fair', 'Poor', 'Damaged', name='asset_condition'), nullable=True),
    sa.Column('condition_after', sa.Enum('Excellent', 'Good', 'Fair', 'Poor', 'Damaged', name='asset_condition'), nullable=True),
    sa.Column('return_remarks', sa.Text(), nullable=True),
    sa.Column('assigned_at', sa.DateTime(), nullable=True),
    sa.Column('returned_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['asset_unit_id'], ['asset_units.id'], ),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.booking_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_booking_unit_assignments_asset_unit_id'), 'booking_unit_assignments', ['asset_unit_id'], unique=False)
    op.create_index(op.f('ix_booking_unit_assignments_booking_id'), 'booking_unit_assignments', ['booking_id'], unique=False)
    op.create_table('maintenance_requests',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('asset_unit_id', sa.UUID(), nullable=False),
    sa.Column('issue', sa.Text(), nullable=False),
    sa.Column('priority', sa.Enum('Low', 'Medium', 'High', 'Critical', name='maintenance_priority'), nullable=False),
    sa.Column('status', sa.Enum('Open', 'In Progress', 'Resolved', 'Closed', name='maintenance_status'), nullable=False),
    sa.Column('reported_by', sa.UUID(), nullable=False),
    sa.Column('assigned_to', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['asset_unit_id'], ['asset_units.id'], ),
    sa.ForeignKeyConstraint(['assigned_to'], ['users.id'], ),
    sa.ForeignKeyConstraint(['reported_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_maintenance_requests_asset_unit_id'), 'maintenance_requests', ['asset_unit_id'], unique=False)
    op.create_table('return_photos',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('booking_id', sa.UUID(), nullable=False),
    sa.Column('asset_unit_id', sa.UUID(), nullable=True),
    sa.Column('image_url', sa.String(length=500), nullable=False),
    sa.Column('caption', sa.Text(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['asset_unit_id'], ['asset_units.id'], ),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.booking_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_return_photos_booking_id'), 'return_photos', ['booking_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_return_photos_booking_id'), table_name='return_photos')
    op.drop_table('return_photos')
    op.drop_index(op.f('ix_maintenance_requests_asset_unit_id'), table_name='maintenance_requests')
    op.drop_table('maintenance_requests')
    op.drop_index(op.f('ix_booking_unit_assignments_booking_id'), table_name='booking_unit_assignments')
    op.drop_index(op.f('ix_booking_unit_assignments_asset_unit_id'), table_name='booking_unit_assignments')
    op.drop_table('booking_unit_assignments')
    op.drop_index(op.f('ix_asset_image_history_asset_model_id'), table_name='asset_image_history')
    op.drop_table('asset_image_history')
    op.drop_index(op.f('ix_asset_health_logs_asset_unit_id'), table_name='asset_health_logs')
    op.drop_table('asset_health_logs')
    op.drop_index(op.f('ix_asset_assignment_history_asset_unit_id'), table_name='asset_assignment_history')
    op.drop_table('asset_assignment_history')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_bookings_user_id'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_asset_model_id'), table_name='bookings')
    op.drop_table('bookings')
    op.drop_index(op.f('ix_audit_logs_timestamp'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_entity_type'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_asset_units_unit_code'), table_name='asset_units')
    op.drop_index(op.f('ix_asset_units_asset_model_id'), table_name='asset_units')
    op.drop_table('asset_units')
    op.drop_index(op.f('ix_asset_images_asset_model_id'), table_name='asset_images')
    op.drop_table('asset_images')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_otp_verifications_user_id'), table_name='otp_verifications')
    op.drop_table('otp_verifications')
    op.drop_index(op.f('ix_asset_models_name'), table_name='asset_models')
    op.drop_index(op.f('ix_asset_models_category'), table_name='asset_models')
    op.drop_table('asset_models')
    # ### end Alembic commands ###
