"""Add preferred_unit_id to Booking

Revision ID: 2d7279ac1700
Revises: 8d39674b9ad3
Create Date: 2026-06-12 18:38:11.960565
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2d7279ac1700'
down_revision: Union[str, None] = '8d39674b9ad3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookings', sa.Column('preferred_unit_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'bookings', 'asset_units', ['preferred_unit_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'bookings', type_='foreignkey')
    op.drop_column('bookings', 'preferred_unit_id')
    # ### end Alembic commands ###
