"""Add AdminApprovalAuditLog table

Revision ID: 8d39674b9ad3
Revises: 72b96e72261a
Create Date: 2026-06-11 19:49:47.305350
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8d39674b9ad3'
down_revision: Union[str, None] = '72b96e72261a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_approval_audit_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('approved_admin_id', sa.UUID(), nullable=False),
    sa.Column('approving_admin_id', sa.UUID(), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['approved_admin_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['approving_admin_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_admin_approval_audit_logs_approved_admin_id'), 'admin_approval_audit_logs', ['approved_admin_id'], unique=False)
    op.create_index(op.f('ix_admin_approval_audit_logs_approving_admin_id'), 'admin_approval_audit_logs', ['approving_admin_id'], unique=False)
    op.create_index(op.f('ix_admin_approval_audit_logs_timestamp'), 'admin_approval_audit_logs', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_admin_approval_audit_logs_timestamp'), table_name='admin_approval_audit_logs')
    op.drop_index(op.f('ix_admin_approval_audit_logs_approving_admin_id'), table_name='admin_approval_audit_logs')
    op.drop_index(op.f('ix_admin_approval_audit_logs_approved_admin_id'), table_name='admin_approval_audit_logs')
    op.drop_table('admin_approval_audit_logs')
    # ### end Alembic commands ###
